version: '3.8'

services:
  backend:
    build: .
    container_name: orb_backend
    ports:
      - "8000:8000"
    # No 'depends_on' mongo because it's external
    depends_on:
      - redis
    env_file:
      - .env
    # We don't override MONGO URIs here anymore; 
    # the ones in your .env will be used directly.
    environment:
      - REDIS_URL=redis://redis:6379
    restart: always

  redis:
    image: redis:alpine
    container_name: orb_redis
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: